Add helthcheck service
web-zavod/svc-commander pull request #1
Opened 2022-04-29 12:21 UTC by Wanderer47

2022-04-29 12:40 UTC, Kuwerin requested changes

2022-04-29 12:40 UTC, Kuwerin commented on Dockerfile
> +RUN mkdir -p scr/
scr — Это что?

2022-05-02 20:50 UTC, Wanderer47 commented on Dockerfile
> +RUN mkdir -p scr/
Так я обозвал scr(source), директорию в которой содержатся все пакеты сервиса.

2022-05-03 14:53 UTC, Kuwerin requested changes

2022-05-05 14:52 UTC, Kuwerin commented on docker-compose.yml
> +      - app
@Wanderer47 суть в том, что `depends_on` влияет на порядок запуска контейнеров. Тут получается, что контейнер с отладочным `grpcox` будет запущен только после того, как запустится твой `app`, но в целом оба контейнера не зависят друг от друга

2022-05-08 08:30 UTC, Kuwerin approved these changes

2022-05-08 17:59 UTC, merged